apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-role
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - pods/exec
  - secrets
  - ingresses
  - services
  - jobs
  - deployments
  - statefulsets
  - cronjobs
  - workflows
  - configmaps
  verbs: ["*"]
